template class VectorGPU<bool>;
template class VectorGPU<short>;
template class VectorGPU<unsigned short>;
template class VectorGPU<int>;
template class VectorGPU<unsigned int>;
template class VectorGPU<long>;
template class VectorGPU<unsigned long>;
template class VectorGPU<long long>;
template class VectorGPU<unsigned long long>;
template class VectorGPU<float>;
template class VectorGPU<double>;
template class VectorGPU<long double>;
template class MatrixGPU<bool>;
template class MatrixGPU<short>;
template class MatrixGPU<unsigned short>;
template class MatrixGPU<int>;
template class MatrixGPU<unsigned int>;
template class MatrixGPU<long>;
template class MatrixGPU<unsigned long>;
template class MatrixGPU<long long>;
template class MatrixGPU<unsigned long long>;
template class MatrixGPU<float>;
template class MatrixGPU<double>;
template class MatrixGPU<long double>;
